// Code generated by Octo (https://github.com/oesand/octo). DO NOT EDIT!
//go:build !octogen

package foo

import (
	"github.com/oesand/octo/octogen"
)

var StructFields = struct {
	Age octogen.FieldDescriptor[Struct, int]
	Name octogen.FieldDescriptor[Struct, string]
	Other octogen.FieldDescriptor[Struct, *Other]
}{
	Age:octogen.FieldDescriptor[Struct, int]{
		Name: "Age",
		Value: func(s *Struct) int {
			return s.Age
		},
	},
	Name:octogen.FieldDescriptor[Struct, string]{
		Name: "Name",
		Value: func(s *Struct) string {
			return s.Name
		},
	},
	Other:octogen.FieldDescriptor[Struct, *Other]{
		Name: "Other",
		Value: func(s *Struct) *Other {
			return s.Other
		},
	},
}
