// Code generated by Octo (https://github.com/oesand/octo). DO NOT EDIT!
//go:build !octogen

package foo

import (
	"github.com/oesand/octo/pm"
)

var StructFields = struct {
	Age pm.FieldDescriptor[Struct, int]
	Name pm.FieldDescriptor[Struct, string]
	Other pm.FieldDescriptor[Struct, *Other]
}{
	Age:pm.FieldDescriptor[Struct, int]{
		Name: "Age",
		Value: func(s *Struct) int {
			return s.Age
		},
	},
	Name:pm.FieldDescriptor[Struct, string]{
		Name: "Name",
		Value: func(s *Struct) string {
			return s.Name
		},
	},
	Other:pm.FieldDescriptor[Struct, *Other]{
		Name: "Other",
		Value: func(s *Struct) *Other {
			return s.Other
		},
	},
}
