package content

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
)

const generatedHeaderText = "// Code generated by Octo (https://github.com/oesand/octo). DO NOT EDIT!\n" +
	"//go:build !octogen\n\n"

func Pkg(path, dir string, ctx RenderContext, blocks []FileBlockRenderer) PackageRenderer {
	return &packageRenderer{
		name:   filepath.Base(path),
		path:   path,
		dir:    dir,
		ctx:    ctx,
		blocks: blocks,
	}
}

type packageRenderer struct {
	name, path, dir string

	ctx    RenderContext
	blocks []FileBlockRenderer
}

func (r *packageRenderer) Name() string {
	return r.name
}

func (r *packageRenderer) Path() string {
	return r.path
}

func (r *packageRenderer) Dir() string {
	return r.dir
}

func (r *packageRenderer) buffer() *bytes.Buffer {
	var b bytes.Buffer

	b.WriteString(generatedHeaderText)
	b.WriteString("package ")
	b.WriteString(r.name)
	b.WriteString("\n\n")

	b.WriteString("import (\n")
	for alias, path := range r.ctx.Imports() {
		b.WriteRune('\t')

		if alias != "" {
			b.WriteString(alias)
			b.WriteRune(' ')
		}

		fmt.Fprintf(&b, "\"%s\"\n", path)
	}

	b.WriteString(")\n")

	for _, fn := range r.blocks {
		b.WriteRune('\n')
		fn.RenderFileBlock(r.ctx, &b)
		b.WriteRune('\n')
	}

	return &b
}

func (r *packageRenderer) Render() []byte {
	return r.buffer().Bytes()
}

func (r *packageRenderer) WriteFile(name string, mode os.FileMode) error {
	buf := r.buffer()

	file, err := os.OpenFile(name, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, mode)
	if err != nil {
		return err
	}

	_, err = buf.WriteTo(file)
	if cerr := file.Close(); err == nil {
		err = cerr
	}

	return err
}
