package content

import (
	"bytes"
	"fmt"
	"path/filepath"
)

const generatedHeaderText = "// Code generated by Octo (https://github.com/oesand/octo). DO NOT EDIT!\n" +
	"//go:build !octogen\n\n"

func Pkg(path, dir string, ctx RenderContext, blocks []FileBlockRenderer) *PkgRenderer {
	return &PkgRenderer{
		name:   filepath.Base(path),
		path:   path,
		dir:    dir,
		ctx:    ctx,
		blocks: blocks,
	}
}

type PkgRenderer struct {
	name, path, dir string

	ctx    RenderContext
	blocks []FileBlockRenderer
}

func (r *PkgRenderer) Name() string {
	return r.name
}

func (r *PkgRenderer) Path() string {
	return r.path
}

func (r *PkgRenderer) Dir() string {
	return r.dir
}

func (r *PkgRenderer) Render() []byte {
	var b bytes.Buffer

	b.WriteString(generatedHeaderText)
	b.WriteString("package ")
	b.WriteString(r.name)
	b.WriteString("\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/oesand/octo\"\n")

	for alias, imp := range r.ctx.Imports() {
		b.WriteString(fmt.Sprintf("\t%s \"%s\"\n", alias, imp))
	}

	b.WriteString(")\n")

	for _, fn := range r.blocks {
		b.WriteRune('\n')
		fn.RenderFileBlock(r.ctx, &b)
		b.WriteRune('\n')
	}

	return b.Bytes()
}
