// Code generated by Octo (https://github.com/oesand/octo). DO NOT EDIT!
//go:build !octogen

package foo

import (
	"github.com/oesand/octo"
	embedded "github.com/oesand/octo/testdata/octogen_tests/InjectAnyVariants/foo/embedded"
	fnc "github.com/oesand/octo/testdata/octogen_tests/InjectAnyVariants/foo/fnc"
	generic "github.com/oesand/octo/testdata/octogen_tests/InjectAnyVariants/foo/generic"
)

func IncludeStruct(container *octo.Container) {
	octo.Inject(container, func(container *octo.Container) *Linked {
		return &Linked{}
	})
	octo.InjectNamed(container, "named", func(container *octo.Container) *Named {
		return &Named{}
	})
	octo.Inject(container, func(container *octo.Container) *Struct {
		return &Struct{
			NestedFunc:   octo.Resolve[*fnc.Struct](container),
			NestedStruct: octo.Resolve[*embedded.Struct](container),
			Linked:       octo.Resolve[*Linked](container),
			Named:        octo.ResolveNamed[*Named](container, "named"),
		}
	})
}

func IncludeFunc(container *octo.Container) {
	octo.Inject(container, func(container *octo.Container) *fnc.Linked {
		return &fnc.Linked{}
	})
	octo.Inject(container, func(container *octo.Container) *fnc.Struct {
		return fnc.NewPtrStruct(
			octo.Resolve[*fnc.Linked](container),
		)
	})
	octo.Inject(container, func(container *octo.Container) fnc.Struct {
		return fnc.NewStruct(
			octo.Resolve[fnc.Linked](container),
		)
	})
	octo.Inject(container, func(container *octo.Container) fnc.Iface {
		return fnc.NewIface(
			octo.Resolve[*fnc.Linked](container),
		)
	})
	octo.InjectNamed(container, "named", func(container *octo.Container) fnc.Iface {
		return fnc.NewIface(
			octo.Resolve[*fnc.Linked](container),
		)
	})
}

func IncludeEmbedded(container *octo.Container) {
	octo.Inject(container, func(container *octo.Container) *embedded.Linked {
		return &embedded.Linked{}
	})
	octo.Inject(container, func(container *octo.Container) *embedded.Struct {
		return &embedded.Struct{
			Base: embedded.Base{
				Link: octo.Resolve[*embedded.Linked](container),
				Super: embedded.Super{
					Link: octo.Resolve[*embedded.Linked](container),
				},
			},
			Link: octo.Resolve[*embedded.Linked](container),
			If:   octo.Resolve[embedded.Iface](container),
		}
	})
}

func IncludeGeneric(container *octo.Container) {
	octo.Inject(container, func(container *octo.Container) *generic.Struct[int, *generic.Generic] {
		return &generic.Struct[int, *generic.Generic]{
			Base: generic.Base[*generic.Generic]{
				Super: generic.Super[*generic.Generic]{
					Link: octo.Resolve[*generic.Linked[*generic.Generic]](container),
				},
				Link: octo.Resolve[*generic.Linked[*generic.Generic]](container),
			},
			Link: octo.Resolve[*generic.Linked[int]](container),
		}
	})
	octo.Inject(container, func(container *octo.Container) *generic.Struct[int, *generic.Generic] {
		return generic.NewStruct(
			octo.Resolve[*generic.Linked[int]](container),
		)
	})
}
